### PR TITLE
Footer area

### PR DESCRIPTION
**Pull request by kilonzi**
Review Request from the latest branch (footer-area)

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Hi there Team
Nice work on this project. It's looking good :clap: You get everything right.
But before you merge to master, I want you to fix these two minor things. I trust you to merge only after making these changes, so **NO** need to submit for code review again.

[REQUIRED]
- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

[REQUIRED]
- [x]  There are some errors in your CSS code. Check them using this CSS [validator](https://jigsaw.w3.org/css-validator/) . Ignore the warnings.

**Review by Torres-ssf — APPROVED** [review]
Congratulation on this project and good luck with the next one. :tada: 
Happy coding :computer:

**Comment by kilonzi** [comment]
All changes are done and HTML + CSS validation have passed

**Pull request merged**
